// Copyright 2026 Alibaba Group Holding Ltd..
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current egress policy
         * @description Returns the currently enforced egress policy and the sidecar's derived
         *     runtime mode metadata.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current policy returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyStatusResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch egress rules
         * @description Merge incoming egress rules with the currently enforced policy.
         *
         *     This endpoint uses merge semantics:
         *     - Existing rules remain unless overridden by incoming rules.
         *     - Incoming rules are applied with higher priority than existing rules.
         *     - If multiple incoming rules refer to the same `target`, the first one wins.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NetworkRule"][];
                };
            };
            responses: {
                /** @description Patch applied successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyStatusResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PolicyStatusResponse: {
            /**
             * @description Operation status reported by the sidecar.
             * @example ok
             */
            status?: string;
            /**
             * @description Derived runtime mode for the current policy.
             * @example deny_all
             */
            mode?: string;
            /**
             * @description Egress sidecar enforcement backend mode.
             * @example dns
             */
            enforcementMode?: string;
            /** @description Optional human-readable reason when the sidecar returns extra context. */
            reason?: string;
            policy?: components["schemas"]["NetworkPolicy"];
        };
        /**
         * @description Egress network policy matching the sidecar `/policy` request body.
         *     If `defaultAction` is omitted, the sidecar defaults to "deny"; passing an empty
         *     object or null results in allow-all behavior at startup.
         */
        NetworkPolicy: {
            /**
             * @description Default action when no egress rule matches. Defaults to "deny".
             * @enum {string}
             */
            defaultAction?: "allow" | "deny";
            /** @description List of egress rules evaluated in order. */
            egress?: components["schemas"]["NetworkRule"][];
        };
        NetworkRule: {
            /**
             * @description Whether to allow or deny matching targets.
             * @enum {string}
             */
            action: "allow" | "deny";
            /**
             * @description FQDN or wildcard domain (e.g., "example.com", "*.example.com").
             *     IP/CIDR not yet supported in the egress MVP.
             */
            target: string;
        };
    };
    responses: {
        /** @description The request was invalid or malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Authentication failed for the egress sidecar. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description The sidecar failed to apply or fetch policy state. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
